#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x11ae19b5, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x6cc42aee, __VMLINUX_SYMBOL_STR(proc_dointvec_minmax) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0xb9d24153, __VMLINUX_SYMBOL_STR(locks_copy_lock) },
	{ 0xf29a148e, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x1ceea77e, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0x619cb7dd, __VMLINUX_SYMBOL_STR(simple_read_from_buffer) },
	{ 0x6bf1c17f, __VMLINUX_SYMBOL_STR(pv_lock_ops) },
	{ 0x4489da02, __VMLINUX_SYMBOL_STR(register_sysctl_table) },
	{ 0x71aa6a87, __VMLINUX_SYMBOL_STR(param_get_int) },
	{ 0x46a8ce42, __VMLINUX_SYMBOL_STR(locks_start_grace) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0xf68285c0, __VMLINUX_SYMBOL_STR(register_inetaddr_notifier) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0xd5c1b04c, __VMLINUX_SYMBOL_STR(svc_print_addr) },
	{ 0x79f62746, __VMLINUX_SYMBOL_STR(svc_sock_update_bufs) },
	{ 0x8507c383, __VMLINUX_SYMBOL_STR(proc_dointvec) },
	{ 0x7ab88a45, __VMLINUX_SYMBOL_STR(system_freezing_cnt) },
	{ 0xc3880471, __VMLINUX_SYMBOL_STR(xdr_decode_netobj) },
	{ 0x20000329, __VMLINUX_SYMBOL_STR(simple_strtoul) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0x52dec438, __VMLINUX_SYMBOL_STR(svc_find_xprt) },
	{ 0xc87c1f84, __VMLINUX_SYMBOL_STR(ktime_get) },
	{ 0x5708b391, __VMLINUX_SYMBOL_STR(remove_proc_entry) },
	{ 0x6fd7dcda, __VMLINUX_SYMBOL_STR(rpc_restart_call) },
	{ 0xfadb58f1, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0x6f8c9737, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0xab757cde, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0x5d8532ee, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x32a1b77e, __VMLINUX_SYMBOL_STR(rpc_force_rebind) },
	{ 0x32c2d725, __VMLINUX_SYMBOL_STR(kthread_create_on_node) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0xa7e4ce5, __VMLINUX_SYMBOL_STR(xdr_reserve_space) },
	{ 0x943845b5, __VMLINUX_SYMBOL_STR(svc_set_client) },
	{ 0x62de687d, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0x9878745c, __VMLINUX_SYMBOL_STR(_atomic_dec_and_lock) },
	{ 0x9e88526, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xdb78c820, __VMLINUX_SYMBOL_STR(rpc_delay) },
	{ 0x44a6d71, __VMLINUX_SYMBOL_STR(vfs_lock_file) },
	{ 0x2c3f9619, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0xf783b36e, __VMLINUX_SYMBOL_STR(proc_mkdir) },
	{ 0xd2f6220a, __VMLINUX_SYMBOL_STR(rpc_call_sync) },
	{ 0xde12acd8, __VMLINUX_SYMBOL_STR(default_llseek) },
	{ 0xd82c8eb3, __VMLINUX_SYMBOL_STR(svc_create) },
	{ 0x4b60b3aa, __VMLINUX_SYMBOL_STR(svc_destroy) },
	{ 0xacecfeb6, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0xfe00fef8, __VMLINUX_SYMBOL_STR(rpc_create) },
	{ 0xa6485b04, __VMLINUX_SYMBOL_STR(freezing_slow_path) },
	{ 0x8f6519fd, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xa5cb60c7, __VMLINUX_SYMBOL_STR(kthread_stop) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x5d0161ec, __VMLINUX_SYMBOL_STR(proc_doulongvec_minmax) },
	{ 0x5792f848, __VMLINUX_SYMBOL_STR(strlcpy) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x78c0fecc, __VMLINUX_SYMBOL_STR(vfs_cancel_lock) },
	{ 0x65ad8a27, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x8ead4d17, __VMLINUX_SYMBOL_STR(svc_process) },
	{ 0xa07a37f0, __VMLINUX_SYMBOL_STR(memchr) },
	{ 0xfd2d5606, __VMLINUX_SYMBOL_STR(svc_rpcb_cleanup) },
	{ 0xbc8ff6d2, __VMLINUX_SYMBOL_STR(up_write) },
	{ 0xf5a6f2d2, __VMLINUX_SYMBOL_STR(init_net) },
	{ 0x25f897a7, __VMLINUX_SYMBOL_STR(down_write) },
	{ 0xfa9570f0, __VMLINUX_SYMBOL_STR(svc_age_temp_xprts_now) },
	{ 0x30e35cf9, __VMLINUX_SYMBOL_STR(flush_signals) },
	{ 0x87023f07, __VMLINUX_SYMBOL_STR(svc_xprt_put) },
	{ 0x9be1a585, __VMLINUX_SYMBOL_STR(simple_transaction_release) },
	{ 0x926cc9c0, __VMLINUX_SYMBOL_STR(__rpc_wait_for_completion_task) },
	{ 0xc67192d1, __VMLINUX_SYMBOL_STR(svc_create_xprt) },
	{ 0x16b021c5, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0xa73b6f3f, __VMLINUX_SYMBOL_STR(locks_init_lock) },
	{ 0xfe029963, __VMLINUX_SYMBOL_STR(unregister_inetaddr_notifier) },
	{ 0x9f80ff1c, __VMLINUX_SYMBOL_STR(locks_release_private) },
	{ 0xa06ff399, __VMLINUX_SYMBOL_STR(unregister_sysctl_table) },
	{ 0x24d95441, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x2eec63c9, __VMLINUX_SYMBOL_STR(xdr_encode_netobj) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0xc0cd3b13, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0x87565c9, __VMLINUX_SYMBOL_STR(locks_lock_inode_wait) },
	{ 0x4482cdb, __VMLINUX_SYMBOL_STR(__refrigerator) },
	{ 0x7e2ac978, __VMLINUX_SYMBOL_STR(wake_up_process) },
	{ 0xf57dfcf2, __VMLINUX_SYMBOL_STR(locks_in_grace) },
	{ 0xb138ce4f, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0x529dbbb7, __VMLINUX_SYMBOL_STR(rpc_run_task) },
	{ 0x52b84d73, __VMLINUX_SYMBOL_STR(param_get_ulong) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x65994f1, __VMLINUX_SYMBOL_STR(xdr_encode_opaque_fixed) },
	{ 0xe5919cb1, __VMLINUX_SYMBOL_STR(xdr_encode_opaque) },
	{ 0xa6bbd805, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x4f6dd8b7, __VMLINUX_SYMBOL_STR(svc_shutdown_net) },
	{ 0xb3f7646e, __VMLINUX_SYMBOL_STR(kthread_should_stop) },
	{ 0x2207a57f, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x1f2a9970, __VMLINUX_SYMBOL_STR(rpc_ntop) },
	{ 0xae69e177, __VMLINUX_SYMBOL_STR(proc_create_data) },
	{ 0xc36915bd, __VMLINUX_SYMBOL_STR(posix_unblock_lock) },
	{ 0xc1cb71c6, __VMLINUX_SYMBOL_STR(svc_exit_thread) },
	{ 0x9c55cec, __VMLINUX_SYMBOL_STR(schedule_timeout_interruptible) },
	{ 0xc350de48, __VMLINUX_SYMBOL_STR(vfs_test_lock) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xf19845ff, __VMLINUX_SYMBOL_STR(simple_transaction_get) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x6df1aaf1, __VMLINUX_SYMBOL_STR(kernel_sigaction) },
	{ 0x3bb5114a, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0x9e61bb05, __VMLINUX_SYMBOL_STR(set_freezable) },
	{ 0x6128b5fc, __VMLINUX_SYMBOL_STR(__printk_ratelimit) },
	{ 0xd2685ad0, __VMLINUX_SYMBOL_STR(svc_xprt_do_enqueue) },
	{ 0x244f784a, __VMLINUX_SYMBOL_STR(svc_prepare_thread) },
	{ 0xf08242c2, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x1fe1e1ad, __VMLINUX_SYMBOL_STR(locks_end_grace) },
	{ 0xb742fd7, __VMLINUX_SYMBOL_STR(simple_strtol) },
	{ 0x9ae83f80, __VMLINUX_SYMBOL_STR(xdr_inline_decode) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x5d1b7fcc, __VMLINUX_SYMBOL_STR(svc_recv) },
	{ 0x97474934, __VMLINUX_SYMBOL_STR(svc_bind) },
	{ 0x61dba4ee, __VMLINUX_SYMBOL_STR(rpc_shutdown_client) },
	{ 0x8ea9bed1, __VMLINUX_SYMBOL_STR(param_ops_uint) },
	{ 0x2919b156, __VMLINUX_SYMBOL_STR(xdr_decode_string_inplace) },
	{ 0x6003bece, __VMLINUX_SYMBOL_STR(__init_rwsem) },
	{ 0xf8105828, __VMLINUX_SYMBOL_STR(svc_wake_up) },
	{ 0xa6f3b40b, __VMLINUX_SYMBOL_STR(rpc_put_task) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=grace,sunrpc";


MODULE_INFO(srcversion, "CF9CC9609868A4415374889");
